### ISSUE TITLE
bug: error to test with jest a module that integrate wagmi

### ISSUE THREAD

**Issue by dancespiele** [wagmi-dev/wagmi#1284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.1

### Current Behavior

when I run the test with jest I get this issue:

```bash
  ● Test suite failed to run

    Must use import to load ES Module: /home/spielrs/nevermined/components-catalog/providers/node_modules/wagmi/dist/index.js

      29 |     logout: () => void;
      30 |     /** Get the status of the wallet */
    > 31 |     getStatus: () => "connecting" | "connected" | "reconnecting" | "disconnected" | undefined;
         |                 ^
      32 |     /** Get all the available chains */
      33 |     getAllAvailableChains: () => Chain[];
      34 |     /** The address of the wallet account */

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:817:21)
      at Object.<anonymous> (src/providers.tsx:31:17)
      at Object.<anonymous> (src/index.ts:32:14)
      at Object.<anonymous> (tests/providers.spec.tsx:32:15)
```

### Expected Behavior

The test shouldn't throw this error

### Steps To Reproduce

1 - clone the repo: `git clone https://github.com/nevermined-io/components-catalog.git`
2 - change the branch: `git checkout provider/implement-connnectkit`
3 - install dependencies: `yarn`
4 - run tests: `yarn test:unit`

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/nevermined-io/components-catalog/tree/provider/implement-connnectkit

**Comment by tmm** [comment]
wagmi recently dropped support for CommonJS and [only supports ESM starting in `0.8`](https://wagmi.sh/docs/migration-guide#commonjs-support-dropped). For Jest to work, you need to [configure it to use ESM.](https://jestjs.io/docs/ecmascript-modules)

**Comment by dancespiele** [comment]
@tmm I tried using this NODE_OPTIONS=--experimental-vm-modules npx jest and having this in the jest config file:*
```js
/** @type {import('ts-jest/dist/types').InitialOptionsTsJest} */
module.exports = {
  verbose: true,
  preset: "ts-jest/presets/default-esm",
  testEnvironment: "jsdom",
  extensionsToTreatAsEsm: ['.ts'],
  setupFilesAfterEnv: ["<rootDir>/tests/jest-setup.ts"],
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
  },
  transform: {
    '^.+\\.m?[tj]sx?$': [
      'ts-jest',
      {
        useESM: true,
      },
    ],
  },
}
```
but I get the same error

**Comment by dancespiele** [comment]
ok the issue was about ConnectKit dependencies
