### ISSUE TITLE
bug: Error: `useClient` must be used within `WagmiConfig` error on vercel deployments

### ISSUE THREAD

**Issue by wesleyfsmith** [wagmi-dev/wagmi#1355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.4

### Current Behavior

When using a version greater than 0.6, when deploying the nextjs app to vercel I receive the following error:

framework-45b23bd899ce37ec.js:1 Error: `useClient` must be used within `WagmiConfig`.

Read more: https://wagmi.sh/docs/WagmiConfig
    at Ae (_app-8add5ac78ac2a28e.js:1:1548790)
    at _app-8add5ac78ac2a28e.js:1:1607043
    at an (_app-8add5ac78ac2a28e.js:1:1607847)
    at vn (_app-8add5ac78ac2a28e.js:1:1616335)
    at xn (_app-8add5ac78ac2a28e.js:1:1616842)
    at Eo (framework-45b23bd899ce37ec.js:1:63195)
    at xi (framework-45b23bd899ce37ec.js:1:120435)
    at bs (framework-45b23bd899ce37ec.js:1:109371)
    at gs (framework-45b23bd899ce37ec.js:1:109299)
    at vs (framework-45b23bd899ce37ec.js:1:109162)
du @ framework-45b23bd899ce37ec.js:1

The strange this is that when I create a production build locally, the issue is not reproducible. It only happens on the vercel deployment. It makes the entire front end crash and become unusable. I'm doing the normal isMounted() check, and version 0.6 works but 0.7 0.8 have this issue when deployed.

### Expected Behavior

It shouldn't throw the error...

### Steps To Reproduce

Any vercel deployment with nextjs using versions 0.7 or 0.8

### Anything else?

![image](https://user-images.githubusercontent.com/3653341/203856107-68938c5c-a90c-4548-b917-33d31601e16f.png)

**Comment by wesleyfsmith** [comment]
Nevermind, this issue was caused by using an older version of rainbowkit with the newest version of wagmi. Upgrading both wagmi and rainbowkit resolved the problem
