### ISSUE TITLE
ContractMethodDoesNotExistError during prepareWriteContract

### ISSUE THREAD

**Issue by kombos** [wagmi-dev/wagmi#1879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.5

### Current Behavior

I'm implementing usePrepareContractWrite alongwith useContractWrite like this: 

```
const { config, error } = usePrepareContractWrite({
    address: nonFungiblePositionManagerContractAddress,
    abi: nonFungiblePositionManagerABI,
    functionName: "safeTransferFrom",
    args: [
      address,
      uniV3StakerContractAddress,
      Number(tokenId),
      [latestIncentiveProgram?.incentiveId],
    ],
    enabled: isConnected && address && tokenId,
    chainId: 1,
    onError(error) {
      console.error(error);
      toast.error(PREPARE_CONTRACT_ERROR, toastConfig);
    },
  });

  const { writeAsync } = useContractWrite({
    ...config,
    onError(error) {
      console.error(error);
      toast.error(WRITE_CONTRACT_ERROR, toastConfig);
    },
  });
```

this is throwing error: 
```
next-dev.js:28 ContractMethodDoesNotExistError: Function "safeTransferFrom" on contract "0xC36442b4a4522E871399CD717aBDD847Ab11FE88" does not exist.

Etherscan: https://etherscan.io/address/0xC36442b4a4522E871399CD717aBDD847Ab11FE88#readContract
    at prepareWriteContract (chunk-55IO54NW.js:2207:11)
    at Object.eval [as queryFn] (index.js:1714:77)
    at Object.fetchFn [as fn] (query.mjs:260:27)
    at run (retryer.mjs:107:31)
    at createRetryer (retryer.mjs:155:5)
    at Query.fetch (query.mjs:314:79)
    at QueryObserver.executeFetch (queryObserver.mjs:177:37)
    at QueryObserver.setOptions (queryObserver.mjs:95:12)
    at eval (index.js:255:14)
    at commitHookEffectListMount (react-dom.development.js:23145:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24921:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24886:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24873:7)
    at commitPassiveMountEffects (react-dom.development.js:24861:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27034:3)
```

not sure why it is looking in read contract section when clearly this is write contract. Please do help. 

### Expected Behavior

write contract transaction execution  should initiate.

**Comment by tmm** [comment]
What ABI are you using? Please put together a complete minimal reproducible example and reopen this issue.

**Comment by kombos** [comment]
this is the abi :
 [{
    "inputs": [
      { "internalType": "address", "name": "from", "type": "address" },
      { "internalType": "address", "name": "to", "type": "address" },
      { "internalType": "uint256", "name": "tokenId", "type": "uint256" },
      { "internalType": "bytes", "name": "_data", "type": "bytes" }
    ],
    "name": "safeTransferFrom",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }],

**Comment by tmm** [comment]
The last argument in `args` is incorrect. It must be either `` `0x${string}` | Uint8Array ``
