### ISSUE TITLE
bug: walletClient compatible with ethers ContractFactory?

### ISSUE THREAD

**Issue by j-5-s** [wagmi-dev/wagmi#2392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.5

### Current Behavior

I'm attempting to create a contract using ethers.js and wagmi but getting a ts trying to pass the walletclient (signer) into ContractFactory:
![Screen Shot 2023-05-20 at 8 56 55 PM](https://github.com/wagmi-dev/wagmi/assets/666455/a967fdeb-211d-4040-a16a-332a1fbf8762)

If ignore the ts error with below i get other errors cause it doesnt thing its a signer
```
_async_to_generator.mjs:6 Uncaught (in promise) Error: invalid signer (argument="signer", value={"chain":{"id":11155111,"network":"sepolia","name":"Sepolia","nativeCurrency":{"name":"Sepolia Ether","symbol":"SEP","decimals":18},"rpcUrls":{"alchemy":{"http":["https://eth-sepolia.g.alchemy.com/v2"],"webSocket":["wss://eth-sepolia.g.alchemy.com/v2"]},"infura":{"http":["https://sepolia.infura.io/v3"],"webSocket":["wss://sepolia.infura.io/ws/v3"]},"default":{"http":["https://rpc.sepolia.org"]},"public":{"http":["https://rpc.sepolia.org"]}},"blockExplorers":{"etherscan":{"name":"Etherscan","url":"https://sepolia.etherscan.io"},"default":{"name":"Etherscan","url":"https://sepolia.etherscan.io"}},"contracts":{"multicall3":{"address":"0xca11bde05977b3631167028862be2a173976ca11","blockCreated":6507670}},"testnet":true},"key":"wallet","name":"Wallet Client","pollingInterval":4000,"transport":{"key":"custom","name":"Custom Provider","retryCount":0,"retryDelay":150,"type":"custom"},"type":"walletClient","uid":"7222dc8b4a4","account":{"address":"0x66c2801e144A0BA4d7F6aFF62f535F312aaF609a","type":"json-rpc"}}, code=INVALID_ARGUMENT, version=contracts/5.7.0)
    at Logger.makeError (index.js:224:1)
    at Logger.throwError (index.js:233:1)
    at Logger.throwArgumentError (index.js:236:1)
    at new ContractFactory (index.js:928:1)
    at eval (DeployContract.tsx:42:17)
    at step (tslib.es6.js:147:1)
```

versions:
```
npm ls ethers
├── ethers@5.7.2
└─┬ wagmi@1.0.5
  └─┬ @wagmi/core@1.0.5
    └─┬ @wagmi/connectors@1.0.3
      ├─┬ @safe-global/safe-apps-provider@0.15.2
      │ └─┬ @safe-global/safe-apps-sdk@7.9.0
      │   └── ethers@5.7.2 deduped
      └─┬ @safe-global/safe-apps-sdk@7.11.0
        └── ethers@5.7.2 deduped
```

### Expected Behavior

im expecting the signer to work as the migration guide [here](https://wagmi.sh/react/migration-guide#provider--signer-terminology) says thats what it is

### Steps To Reproduce

run code as shown above and below:
```ts
   const { data: walletClient } = useWalletClient();

  const handleSubmit = async (evt: FormEvent<HTMLFormElement>) => {
    evt.preventDefault();
    const NFT = new ContractFactory(
      NFTContract.abi,
      NFTContract.bytecode,
      walletClient as any
    );
    console.log(NFT);
    const nft = await NFT.deploy(
      'MyNFT',
      'MNFT'
    )
    await nft.deployed();
    console.log(nft);
  };
  ```

**Comment by idlatest** [comment]
I am also having this exact issue
