### ISSUE TITLE
bug: TypeError: Cannot convert a BigInt value to a number

### ISSUE THREAD

**Issue by chrehman** [wagmi-dev/wagmi#2428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.6

### Current Behavior

 Works fine in local development but when i deploy my react build on vercel server it gives me this error when i try to read contract variable with the help of useContractRead Hook.
 
 TypeError: Cannot convert a BigInt value to a number 64:w3m-account-context.ts
    at Math.pow (<anonymous>)
    at l (toHex.ts:173:21)
    at param (encodeAbiParameters.ts:211:16)
    at h (encodeAbiParameters.ts:101:12)
    at n.params (encodeAbiParameters.ts:68:25)
    at p (encodeAbiParameters.ts:43:26)
    at c (encodeFunctionData.ts:58:9)
    at readContract.ts:79:20
    at d (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)

**Comment by tmm** [comment]
Closing in favor of https://github.com/wagmi-dev/viem/issues/582
