### ISSUE TITLE
No wagmi config found. Ensure you have set up a config: https://wagmi.sh/react/config

### ISSUE THREAD

**Issue by jusdy** [wagmi-dev/wagmi#2480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.5

### Current Behavior

I had setup the wagmi several days ago and it had been working until yesterday
But today, i am facing such error when i run the application. the current one is Create-React-App.

The only thing that I added was installing @wagmi/core module and I think the issue was coming after that, it's not still working even though i uninstalled the module.

Please help me to resolve this..
``
Uncaught runtime errors:
×
ERROR
No wagmi config found. Ensure you have set up a config: https://wagmi.sh/react/config
    at getConfig (http://localhost:3000/static/js/bundle.js:58351:11)
    at A.getAccount (http://localhost:3000/static/js/bundle.js:59939:7)
    at Object.getAccount (http://localhost:3000/static/js/bundle.js:60562:28)
    at new kt (http://localhost:3000/static/js/vendors-node_modules_web3modal_ui_dist_index_js.chunk.js:4046:101)
    at TemplateInstance._clone (http://localhost:3000/static/js/vendors-node_modules_dijkstrajs_dijkstra_js-node_modules_encode-utf8_index_js-node_modules_mo-52fd4c.chunk.js:4866:138)
    at ChildPart._commitTemplateResult (http://localhost:3000/static/js/vendors-node_modules_dijkstrajs_dijkstra_js-node_modules_encode-utf8_index_js-node_modules_mo-52fd4c.chunk.js:5143:33)
    at ChildPart._$setValue (http://localhost:3000/static/js/vendors-node_modules_dijkstrajs_dijkstra_js-node_modules_encode-utf8_index_js-node_modules_mo-52fd4c.chunk.js:5023:12)
    at TemplateInstance._update (http://localhost:3000/static/js/vendors-node_modules_dijkstrajs_dijkstra_js-node_modules_encode-utf8_index_js-node_modules_mo-52fd4c.chunk.js:4915:16)
    at ChildPart._commitTemplateResult (http://localhost:3000/static/js/vendors-node_modules_dijkstrajs_dijkstra_js-node_modules_encode-utf8_index_js-node_modules_mo-52fd4c.chunk.js:5153:16)
    at ChildPart._$setValue (http://localhost:3000/static/js/vendors-node_modules_dijkstrajs_dijkstra_js-node_modules_encode-utf8_index_js-node_modules_mo-52fd4c.chunk.js:5023:12)``

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
