### ISSUE TITLE
Cannot read properties of undefined (reading 'queryClient')bug: <title>

### ISSUE THREAD

**Issue by chibuzoraustine** [wagmi-dev/wagmi#2658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.3

### Current Behavior

This is really frustrating. why does wagmi feel buggy all of a sudden. nothing works anymore geez. i keep getting this error :

```
Cannot read properties of undefined (reading 'queryClient')
TypeError: Cannot read properties of undefined (reading 'queryClient')
    at WagmiConfig (http://localhost:3000/static/js/bundle.js:122154:22)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:54106:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:57392:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:58688:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:43698:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:43742:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:43799:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:63673:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:62920:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:62843:9)
```

### Steps To Reproduce

Everything is set up properly. Here is my code

```js
import {
  configureChains,
  createConfig,
  WagmiConfig,
} from 'wagmi';
import { mainnet, bsc, arbitrum } from 'wagmi/chains';
import { alchemyProvider } from 'wagmi/providers/alchemy';
import { publicProvider } from 'wagmi/providers/public';

import {
  RainbowKitProvider,
  darkTheme,
  getDefaultWallets,
} from '@rainbow-me/rainbowkit';

const { chains, publicClient } = configureChains(
  [mainnet, arbitrum, bsc],
  [
    alchemyProvider({ apiKey: "xxxxxx" }),
    publicProvider()
  ]
);

const projectId = "xxxxxxx";

const { connectors } = getDefaultWallets({
  appName: 'Sync main',
  projectId: projectId,
  chains
});

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors,
  publicClient
})

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    {/* <ChakraProvider> */}
      <WagmiConfig client={wagmiConfig}>
        <RainbowKitProvider chains={chains} theme={darkTheme()} >
          <App />
        </RainbowKitProvider>
      </WagmiConfig>
    {/* </ChakraProvider> */}
  </React.StrictMode >
);
```

Please can anyone tell me what i'm doing wrong.

**Comment by tmm** [comment]
Use the `config` prop instead of `client`

https://wagmi.sh/react/WagmiConfig#config
