### ISSUE TITLE
bug: @wagmi/core sendTransaction

### ISSUE THREAD

**Issue by arganjava** [wagmi-dev/wagmi#2670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.3

### Current Behavior

connect to trust wallet success but when i tried to sendTransaction using @wagmi/core error in browser console

```
main.js:50 {context: 'client'} 'Unknown method(s) requested'
LOG @ browser.js:202
(anonymous) @ browser.js:266
M2.request @ index.ts:5
await in M2.request (async)
request @ lodash.js:10
request @ lodash.js:10
request @ lodash.js:10
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
sendTransaction @ sendTransaction.ts:176
sendTransaction @ wallet.ts:540
sendTransaction2 @ chunk-LAFZBYO7.js:2789
await in sendTransaction2 (async)
document.getElementById.onclick @ main.js:50
Show 14 more frames
getTransactionError.ts:22 Uncaught (in promise) TransactionExecutionError: An unknown RPC error occurred.

Request Arguments:
  from:   0x5b6183f79418E397A10779319dbE39539C21f4Ea
  to:     0x79280d9DDb2753f1fdB85924c81ECB831AB9C8c5
  value:  0.0000000000001 ETH
  gas:    21000

Details: Unknown method(s) requested
Version: viem@1.2.5
    at getTransactionError (getTransactionError.ts:22:10)
    at sendTransaction (sendTransaction.ts:181:11)
    at async sendTransaction2 (chunk-LAFZBYO7.js:2789:16)
    at async document.getElementById.onclick (main.js:50:20)
```

### Expected Behavior

expected wallet should show popup for confirmation

### Steps To Reproduce

1. npm install
2. npm run dev
3. connect wallet and scan qr and success
4. sendTransaction by click button **Send TX**
5. Error 

please clone and try running code at https://github.com/arganjava/web3modal-wagmi-html

please help and thank you 

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/arganjava/web3modal-wagmi-html

**Comment by arganjava** [comment]
fix by this https://github.com/wagmi-dev/wagmi/issues/2161 thank you
