### ISSUE TITLE
bug:  "fromMiliseconds" is not exported by "node_modules/@walletconnect/time/dist/cjs/index.js"

### ISSUE THREAD

**Issue by victorpavlenko** [wagmi-dev/wagmi#2753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

Build with rollup v3.25.3 
With Wagmi: 0.0.12 this working.

```
[!] RollupError: "fromMiliseconds" is not exported by "node_modules/@walletconnect/time/dist/cjs/index.js", imported by "node_modules/@walletconnect/relay-auth/dist/esm/api.js".
https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module
node_modules/@walletconnect/relay-auth/dist/esm/api.js (3:9)
1: import * as ed25519 from "@stablelib/ed25519";
2: import { randomBytes } from "@stablelib/random";
3: import { fromMiliseconds } from "@walletconnect/time";
            ^
4: import { JWT_IRIDIUM_ALG, JWT_IRIDIUM_TYP, KEY_PAIR_SEED_LENGTH, } from "./constants";
5: import { decodeIss, decodeJWT, encodeData, encodeIss, encodeJWT, } from "./utils";
    at error (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:349:30)
    at Module.error (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:15060:16)
    at Module.traceVariable (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:15485:29)
    at ModuleScope.findVariable (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:14010:39)
    at FunctionScope.findVariable (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:8570:38)
    at Identifier.bind (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:9730:40)
    at CallExpression.bind (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:7350:23)
    at CallExpression.bind (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:11296:15)
    at AssignmentPattern.bind (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:7350:23)
    at FunctionDeclaration.bind (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:7346:28)
    at ExportNamedDeclaration.bind (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:12079:27)
    at Program.bind (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:7346:28)
    at Module.bindReferences (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:15056:18)
    at Graph.sortModules (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:26110:20)
    at Graph.build (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:25994:14)
    at /Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:26911:13
    at catchUnfinishedHookActions (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:26167:16)
    at Object.rollupInternal (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/rollup.js:26906:5)
    at Task.run (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/watch.js:250:22)
    at Watcher.run (/Users/sasa/shop-widgets/node_modules/rollup/dist/shared/watch.js:182:13)
```

### Expected Behavior

Just should work

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
