### ISSUE TITLE
TransactionNotFoundError: Transaction with hash "0x00...." could not be found.

### ISSUE THREAD

**Issue by Stenor5** [wagmi-dev/wagmi#2799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

Here is the [https://sepolia.etherscan.io/tx/0x9cb20323e654abbba7a3bdc3d4f5450e0d345b709722179189655306548e079c](transaction) with hash `0x9cb20323e654abbba7a3bdc3d4f5450e0d345b709722179189655306548e079c` on sepolia testnet.
I was trying to fetch transaction using below code. 
```js
import { fetchTransaction } from '@wagmi/core'
 
const transaction = await fetchTransaction({
  hash: '0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060',
})
```

but it says 
```
TransactionNotFoundError: Transaction with hash "0x9cb20323e654abbba7a3bdc3d4f5450e0d345b709722179189655306548e079c" could not be found.

Version: viem@1.4.1
    at getTransaction (getTransaction.ts:109:1)
    at async useAccountManagerContract.ts:63:1
    at async handleLoad (AccountMangeModal.tsx:115:1)
```

**Comment by tmm** [comment]
Could be whatever RPC you were using. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
