### ISSUE TITLE
bug:  Rollup failed to resolve import "@safe-globalThis/safe-apps-sdk" from "node_modules/@wagmi/connectors/dist/safe.js".

### ISSUE THREAD

**Issue by roninjin10** [wagmi-dev/wagmi#2989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.1

### Current Behavior

See this error message when trying to build in vite

```
Rollup failed to resolve import "@safe-globalThis/safe-apps-sdk" from "/Users/willcory/optimism-starter/node_modules/@wagmi/connectors/dist/safe.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@safe-globalThis/safe-apps-sdk" from "/Users/willcory/optimism-starter/node_modules/@wagmi/connectors/dist/safe.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///Users/willcory/optimism-starter/node_modules/vite/dist/node/chunks/dep-df561101.js:48142:27)
    at onRollupWarning (file:///Users/willcory/optimism-starter/node_modules/vite/dist/node/chunks/dep-df561101.js:48174:9)
    at onwarn (file:///Users/willcory/optimism-starter/node_modules/vite/dist/node/chunks/dep-df561101.js:47902:13)
    at file:///Users/willcory/optimism-starter/node_modules/rollup/dist/es/shared/node-entry.js:24250:13
    at Object.logger [as onLog] (file:///Users/willcory/optimism-starter/node_modules/rollup/dist/es/shared/node-entry.js:25924:9)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/willcory/optimism-starter/node_modules/rollup/dist/es/shared/node-entry.js:24836:26)
    at file:///Users/willcory/optimism-starter/node_modules/rollup/dist/es/shared/node-entry.js:24796:26
```

I get it to shut up by adding these modules as external to tell vite to not bundle them but now I'm scared my app will break unexpectedly

```typescript

/**
 * @see https://vitejs.dev/config/
 */
export default defineConfig({
  build: {
    rollupOptions: {
      // this is included because it breaks the build if not included
      // this is almost certainly a bug in wagmi (or these libraries transatively
      // and likely can be removed in the future
      external: [
        "@safe-globalThis/safe-apps-provider",
        "@safe-globalThis/safe-apps-sdk",
      ],
    },
  },
}
```

### Expected Behavior

Should build without error warnings by default

### Steps To Reproduce

npm install wagmi and use wagmi in your vite project with the following config

```ts
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import { vitePluginEvmts } from "@evmts/vite-plugin";

/**
 * @see https://vitejs.dev/config/
 */
export default defineConfig({
  build: {
    rollupOptions: {
      // this is included because it breaks the build if not included
      // this is almost certainly a bug in wagmi (or these libraries transatively
      // and likely can be removed in the future
      external: [
        "@safe-globalThis/safe-apps-provider",
        "@safe-globalThis/safe-apps-sdk",
      ],
    },
  },
  /**
   * Defines global constant replacments
   * @see https://vitejs.dev/config/shared-options.html#define
   */
  define: {
    global: "globalThis",
  },
  resolve: {
    /**
     * Polyfills nodejs imports
     * @see https://vitejs.dev/config/shared-options.html#resolve-alias
     */
    alias: {
      process: "process/browser",
      util: "util",
    },
  },
  /**
   * Enables react
   * @see https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md
   */
  plugins: [react(), vitePluginEvmts()],
});

```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/ethereum-optimism/optimism-starter/tree/migrate-evmts

### Anything else?

The reproducible example includes the workaround. To reproduce you must delete the `build` key in the vite.config.ts

**Comment by roninjin10** [comment]
Apparently this exists in the wagmi cli templates too. I opened this pr and forgot about it https://github.com/wagmi-dev/create-wagmi/pull/73/files

**Comment by roninjin10** [comment]
Closed duplicate issue in create wagmi cli repo as it’s not a bug in the template
