### ISSUE TITLE
[bug] usePrepareContractWrite and useContractWrite always returns undefined for write

### ISSUE THREAD

**Issue by wuichen** [wagmi-dev/wagmi#794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.0

### Current Behavior

``` 
  const { config } = usePrepareContractWrite({
    addressOrName: PaymentsAddress.address,
    contractInterface: PaymentsAbi.abi,
    functionName: 'payProduct',
    enabled: true,
    args: [walletAddress, 12, 22, product.id],
    onSettled(data, error) {
      console.log('Settled', { data, error });
    },
  });
```

onSettled is always returning gasLimit issue and cause write to be undefined. how do i set gaslimit in usePrepareContractWrite

**Comment by wuichen** [comment]
figured out its due to gaslimit issue. for future reference, this can be checked from using onSettled callback in usePrepareContractWrite and set an gasLimit object in args

**Comment by Geczy** [comment]
@wuichen can you show an example ?

**Comment by oussamajabnouni** [comment]
@wuichen a example would be helpful

**Comment by wuichen** [comment]
i added gaslimit in the last argument like this to make it work

```

  const { config } = usePrepareContractWrite({
    addressOrName: PaymentsAddress.address,
    contractInterface: PaymentsAbi.abi,
    functionName: 'payProduct',
    enabled: walletAddress,
    args: [
      walletAddress,
      {
        gasLimit: 1300000,
        value:2
      },
    ],
    onSettled(data, error) {
      console.log('Settled', { data, error });
    },
  });
```

**Comment by akcgjc007** [comment]
It would be better to add this in the [docs](https://wagmi.sh/docs/prepare-hooks/usePrepareContractWrite#usage)

**Comment by akcgjc007** [comment]
Can't send 1 ETH. 
Throwing overflow error:

```
{data: undefined, error: Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow…}
data: undefined
error: Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1000000000000000000, code=NUMERIC_FAULT, version=bignumber/5.7.0) at Logger.makeError (webpack-internal:///./node_modules/@ethersproject/logger/lib.esm/index.js:231:23) at Logger.throwError (webpack-internal:///./node_modules/@ethersproject/logger/lib.esm/index.js:240:20) at throwFault (webpack-internal:///./node_modules/@ethersproject/bignumber/lib.esm/bignumber.js:307:19) at BigNumber.from (webpack-internal:///./node_modules/@ethersproject/bignumber/lib.esm/bignumber.js:212:17) at eval (webpack-internal:///./node_modules/@ethersproject/contracts/lib.esm/index.js:192:93) at Generator.next (<anonymous>) at fulfilled (webpack-internal:///./node_modules/@ethersproject/contracts/lib.esm/index.js:21:58)
code: "NUMERIC_FAULT"
fault: "overflow"
operation: "BigNumber.from"
reason: "overflow"
value: 1000000000000000000
message: "overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault=\"overflow\", operation=\"BigNumber.from\", value=1000000000000000000, code=NUMERIC_FAULT, version=bignumber/5.7.0)"
stack: "Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault=\"overflow\", operation=\"BigNumber.from\", value=1000000000000000000, code=NUMERIC_FAULT, version=bignumber/5.7.0)\n    at Logger.makeError (webpack-internal:///./node_modules/@ethersproject/logger/lib.esm/index.js:231:23)\n    at Logger.throwError (webpack-internal:///./node_modules/@ethersproject/logger/lib.esm/index.js:240:20)\n    at throwFault (webpack-internal:///./node_modules/@ethersproject/bignumber/lib.esm/bignumber.js:307:19)\n    at BigNumber.from (webpack-internal:///./node_modules/@ethersproject/bignumber/lib.esm/bignumber.js:212:17)\n    at eval (webpack-internal:///./node_modules/@ethersproject/contracts/lib.esm/index.js:192:93)\n    at Generator.next (<anonymous>)\n    at fulfilled (webpack-internal:///./node_modules/@ethersproject/contracts/lib.esm/index.js:21:58)"
[[Prototype]]: Object
[[Prototype]]: Object
```

**Comment by jxom** [comment]
If you're needing to manually set a gas limit, this probably means that you do not have any funds in your wallet or the contract is reverting. Are you sure you need to manually define a gas limit?
